Hw2
ajluxey/test-guru pull request #2
Opened 2021-06-12 18:06 UTC by ajluxey

2021-06-13 20:06 UTC, VidgarVii requested changes

2021-06-13 20:06 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
задание создать модельки и миграции

2021-06-13 20:06 UTC, VidgarVii commented on db/migrate/20210612173146_add_category_title_null_constraint.rb
> +    change_column_null(:categories, :title, false)
не надо добавлять отдельные миграции для изменения полей в одном ПР.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу.
Пример
```
t.string :title, null: false

2021-06-13 20:06 UTC, VidgarVii commented on db/migrate/20210612173514_create_tests.rb
> +
нужно добавить связь с Автором! теста
т.е. у теста должен быть еще автор

2021-06-13 20:09 UTC, ajluxey commented on db/migrate/20210612173146_add_category_title_null_constraint.rb
> +    change_column_null(:categories, :title, false)
ой, это было вызвано неправильно понятым заданием. Скажите, мне теперь откатиться до уровня предыдущего задания и создать заново миграции, учитывающие все эти правки?

2021-06-15 06:07 UTC, VidgarVii requested changes

2021-06-15 06:07 UTC, VidgarVii commented on db/migrate/20210614211949_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
лучше назвать поле author_id.
Так как по логике нам надо создать ассоциацию как автор теста
т.е. получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference
```

2021-06-15 06:07 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации надо удалить. так как они всё ровно объявлены не корректно

2021-06-15 13:35 UTC, ajluxey commented on app/models/answer.rb
> +  belongs_to :question
хорошо, это произошло автоматом, после применения миграций

2021-06-16 16:21 UTC, merged