Hw4
ajluxey/test-guru pull request #4
Opened 2021-06-28 22:15 UTC by ajluxey

2021-06-29 08:28 UTC, VidgarVii requested changes

2021-06-29 08:28 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2021-06-29 08:28 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Смотри пример тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-06-29 08:28 UTC, VidgarVii commented on app/models/test.rb
> +  has_and_belongs_to_many :is_started_by_users, join_table: 'users_start_tests', class_name: 'User'
ассоциация `has_and_belongs_to_many` почти не используется
в 90% случаев или больше используют `has_many through`, потому что ХБТМ довольно негибкий вариант и если вдруг (а это "вдруг" либо почти всегда планируется, либо все равно случается) понадобится большая гибкость и какая-то логика, относящаяся к связи, то потом переводить из одной связи в другую занятие очень затратное
проще изначально использовать ХМФ

(в текущем приложении в дальнейшем понадобится добавлять логику в связь между пользователями и тестами, поэтому точно нужно реализовывать связь через ХМФ)

2021-06-29 08:28 UTC, VidgarVii commented on app/models/test.rb
>          .where(categories: { title: cat_title })
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2021-06-29 08:28 UTC, VidgarVii commented on app/models/test.rb
>          .where(categories: { title: cat_title })
в сидах так же надо отрефачить код. Убрать обращение к id _id. И передавать сами объекты
пример author: users[0]

2021-06-30 07:04 UTC, VidgarVii requested changes

2021-06-30 07:04 UTC, VidgarVii commented on app/models/test.rb
> +           class_name: 'UsersStartTest',
class_name вроде как совпадает с названием ассоциации. можно не писать явно этот  class_name
foreign_key тоже определяется по имени ассоциации. попробуй убрать на 3 строке

2021-06-30 07:04 UTC, VidgarVii commented on app/models/test.rb
> +           dependent: :destroy
в has_many through достаточно 1 раз указать dependent

2021-06-30 07:04 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins(:category)
тут писать Test нет смысла. Начинай сразу с join
Так как обращение и так идёт к self. т.е. к Тесту

2021-06-30 07:04 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins(:users_start_tests).where('user_id = ?', id).where(level: n)
протестируй метод. тут ошибка

2021-06-30 20:15 UTC, ajluxey commented on app/models/test.rb
> +           class_name: 'UsersStartTest',
foreign_key не получается убрать - перестает работать

2021-07-01 11:07 UTC, merged