Hw5
ajluxey/test-guru pull request #5
Opened 2021-07-01 23:44 UTC by ajluxey

2021-07-02 14:23 UTC, VidgarVii requested changes

2021-07-02 14:23 UTC, VidgarVii commented on app/models/answer.rb
> +  scope :correct, -> { where(correct: true) }
скоупы по сути являются методами класса и их рекомендуют писать после ассоциаций и валидаций

2021-07-02 14:23 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2021-07-02 14:23 UTC, VidgarVii commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
не очень понятно как валидация в модели Вопрос будет препятствовать созданию новых ответов в количестве больше 4... она же не будет вызываться, когда ты будешь добавлять новые ответы к вопросу - вызываются валидации того класса, объекты которого создаются

при создании нового объекта класса Ответ вызываются валидации класса Ответ, а не класса Вопрос

видимо ты не проверяла работу этой валидации

2021-07-02 22:30 UTC, ajluxey commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
Так, я вроде переделал, но я сделал так, что у вопроса может быть от нуля вопросов.
Просто, если сделать так, что вопрос не будет валидным, если количество ответов на него не входит в диапазон (1..4), то получится, что нам придётся создавать вопрос с помощью Question.new(). При этом, он не будет иметь id, что значит, что мы не сможем сохранить объект ответа на вопрос, т.к. в поле question id будет записываться nil (объект ответа будет не валиден). Получился замкнутый круг, который я не могу разрешить.

Поэтому в модели Ответ, сделал проверку "количество принадлежащих вопросов" == 4 , что является потолком.

2021-07-03 14:59 UTC, VidgarVii requested changes

2021-07-03 14:59 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:question, 'question can contain max 4 answers') if question.answers.count == 4
наверное должно быть не ==, а >=
простоя логика.  Ведь 5,6,7 ответа для 1 вопроса тоже должен быть не валидный

2021-07-03 14:59 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_answer_count
сейчас если у вопроса есть 4 ответа. То при обновлении ответа будет ошибка валидации
Надо указывать когда должна использоваться данная валидация. Т.е. только при создании ресурса

2021-07-03 14:59 UTC, VidgarVii commented on app/models/test.rb
> +  scope :all_by_category, ->(cat_title) do
при чём тут кот? давай нормальные названия

2021-07-03 14:59 UTC, VidgarVii commented on db/migrate/20210614211949_create_tests.rb
> +      t.index [:title, :level], unique: true
поезд этих миграций уже уехал. В новом ПР делай новые миграции

2021-07-03 14:59 UTC, VidgarVii commented on db/migrate/20210619103500_create_join_table_users_start_tests.rb
>      create_join_table :users, :tests, table_name: :users_start_tests  do |t|
тут лучше использовать не join table
А создавай полноценную модель с 2 ФК для юзеров и тестов.
Эта модель и таблица будет расширяться

2021-07-03 14:59 UTC, VidgarVii commented on db/migrate/20210619103500_create_join_table_users_start_tests.rb
> +      # t.index [:test_id, :user_id]
муссорные комментарии надо удалять

2021-07-05 07:06 UTC, VidgarVii requested changes

2021-07-05 07:06 UTC, VidgarVii commented on app/models/user.rb
>    def get_passed_tests_with_level(n)
что такое n?
не сокращай

2021-07-05 07:06 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins(:users_tests_progress).where('user_id = ?', id).where('passed').where(level: n)
.where('passed') нет такого выражения. Перепровеь метод

2021-07-05 14:27 UTC, ajluxey commented on app/models/user.rb
> +    Test.joins(:users_tests_progress).where('user_id = ?', id).where('passed').where(level: n)
почему? passed это булева переменная, я перепроверил и оно работает. Или вы имеете в виду, что это должно быть оформлено по правилам SQL?

2021-07-06 23:58 UTC, merged