Hw6. Rails Controllers
ajluxey/test-guru pull request #6
Opened 2021-07-07 02:24 UTC by ajluxey

Сгенерирован контроллер, описаны методы из задания, задействованы колбэки, а так же использовался перехват ошибок

2021-07-07 09:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  layout false
этого точно не надо делать.
попробуй webpacker:install
перед этим надо еще node.js установить
отпиши мне будем разбираться

2021-07-07 09:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    # Я знаю, что не совсем корректно "наводить красоту" в контроллере и лучше делать это во View
красота должна быть везде.

2021-07-07 09:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: Question.find(params[:id]).body
Question.find(params[:id] вызывается не сколько раз. Есть смысл вывести в колбек

2021-07-07 09:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.create!(question_params)
здесь будет создан вопрос, без привязки к тесту
даже правильней сказать будет попытка создать вопрос
потому что если в модели `Question` есть строка `belongs_to :test`, то рельсы не разрешат его создать без указания валидного `test_id`

используй методы ассоциаций 
@test.questions.new

так же вопрос может оказаться не валидным. Надо проверять этот кейс. Если вопрос не записался, то надо заного рендерить юзеру форму.
А при успехе отправлять на какую-нибудь страницу. Например страницу самого вопроса

2021-07-07 09:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.find(params[:id]).destroy
тоже самое. вопрос удалили. А что дальше? Надо юзера куда-то отправить

2021-07-07 10:09 UTC, ajluxey commented on app/controllers/questions_controller.rb
> +    Question.create!(question_params)
Там же используется метод QuestionsController#question_params, в котором происходит отсечение лишних аргументов запроса (params.require(...).permit(...)), а так же, с помощью метода merge, происходит склеивание с хэшем { test: @test }. Так что вопрос создается, а так же корректно привязывается к нужному тесту.
Про остальное - спасибо. В скором времени исправлю.

2021-07-08 07:19 UTC, VidgarVii requested changes

2021-07-08 07:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      question.save
тут можно сразу писать` if question.save`

2021-07-08 07:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to :action => 'new'
если ресурс создан, общей практикой является отправить юзера на этот ресурс
Самый простой вариант это сделать так
`redirect_to @question`
Очень важно, чтобы это была инстанс переменная. Так её будет видеть представление (в след уроке будет пользоваться)
Если ресурс не создался. Рендерим званого форму. (при рендере вся страница браузера не будет перезагружаться. Но контент поменяется) Объект будет содержать ошибки валидации. (тоже в след уроке)
**render :new**

2021-07-08 07:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to :action => 'show', :id => @question.test.id
redirect_to @question

2021-07-10 12:00 UTC, merged